config:
  target: "http://localhost:3001"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up

scenarios:
    flow:
      - get:
          url: "/25173"
          expect:
            - statusCode: 200
